[workspace]
members = [
	"client/consensus/common",
	"client/consensus/relay-chain",
	"client/consensus/filtering",
	"client/consensus/filtering/runtime-api",
	"client/network",
	"client/service",
	"pallets/author-inherent",
	"pallets/author-height-filter",
	"pallets/author-slot-filter",
	"pallets/aura-style-filter",
	"pallets/parachain-system",
	"pallets/xcm-handler",
	"pallets/account-set",
	"primitives/core",
	"primitives/parachain-inherent",
	"rococo-parachains/",
	"rococo-parachains/pallets/parachain-info",
	"rococo-parachains/primitives",
	"rococo-parachains/runtime",
	"test/runtime",
	"test/client",
	"test/service",
	"test/relay-sproof-builder",
]

[profile.release]
panic = "unwind"
