[package]
name = "parachains-common"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Logic which is common to all parachain runtimes"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
# External dependencies
codec = { package = 'parity-scale-codec', version = '2.3.0', features = ['derive'], default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }

# Substrate dependencies
sp-consensus-aura = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
sp-std = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
sp-io = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
frame-executive = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
frame-support = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
frame-system = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
pallet-balances = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
sp-runtime = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
sp-core = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
node-primitives = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }

# Polkadot dependencies
polkadot-runtime-common = { git = 'https://github.com/purestake/polkadot', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
polkadot-primitives = { git = 'https://github.com/purestake/polkadot', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
xcm = { git = 'https://github.com/purestake/polkadot', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
xcm-executor = { git = 'https://github.com/purestake/polkadot', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }

# Local dependencies
pallet-collator-selection = { path = '../../pallets/collator-selection', default-features = false }

[dev-dependencies]
sp-io = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }
pallet-authorship = { git = 'https://github.com/purestake/substrate', default-features = false , branch = "moonbeam-polkadot-v0.9.11" }

[build-dependencies]
substrate-wasm-builder = { git = 'https://github.com/purestake/substrate', branch = "moonbeam-polkadot-v0.9.11" }

[features]
default = ["std"]
std = [
	'codec/std',
	'scale-info/std',
	'sp-consensus-aura/std',
	'sp-std/std',
	'sp-io/std',
	'frame-support/std',
	'frame-executive/std',
	'frame-system/std',
	'pallet-collator-selection/std',
	'pallet-balances/std',
	'node-primitives/std',
	'polkadot-runtime-common/std',
	'polkadot-primitives/std',
]
